[package]
name = "dkimproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
cfdkim = "0.3.0"
mailparse = "0.14"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.0"
tokio = { version = "1.35.1", features = ["full"] }
